name: Update APT Repo with Termuxify

on:
  workflow_dispatch:

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout APT Repo
        uses: actions/checkout@v3

      - name: Set up Git for pushing
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Clone termuxify source repo
        run: |
          git clone https://github.com/Ayanrajpoot10/termuxify.git termuxify-src

      - name: Install build tools
        run: |
          sudo apt update
          sudo apt install -y dpkg-dev build-essential devscripts

      - name: Build the .deb package
        run: |
          cd termuxify-src
          # Create build script
          cat > build.sh << 'EOF'
          #!/data/data/com.termux/files/usr/bin/bash
          set -e

          VERSION="0.1.1"
          PKGNAME="termuxify"
          DEB_DIR="debian/${PKGNAME}"
          USR_DIR="${DEB_DIR}/data/data/com.termux/files/usr"
          BIN_DIR="${USR_DIR}/bin"
          SHARE_DIR="${USR_DIR}/share/${PKGNAME}"

          rm -rf "$DEB_DIR" "${PKGNAME}_${VERSION}.deb"

          mkdir -p "$DEB_DIR/DEBIAN" "$BIN_DIR" "$SHARE_DIR/colors" "$SHARE_DIR/fonts"

          for script in control postinst prerm postrm; do
              [[ -f "debian/$script" ]] || { echo "Error: debian/$script not found"; exit 1; }
              sed -i 's/\r$//' "debian/$script"
              install -m $([ "$script" = "control" ] && echo "644" || echo "755") "debian/$script" "$DEB_DIR/DEBIAN/$script"
          done

          install -m755 termuxify.sh "$BIN_DIR/termuxify.sh"
          cp -a colors/. "$SHARE_DIR/colors/"
          cp -a fonts/. "$SHARE_DIR/fonts/"

          chmod 755 "$DEB_DIR"/DEBIAN/post* "$DEB_DIR"/DEBIAN/pre* 2>/dev/null || true

          chmod 755 "$DEB_DIR/DEBIAN"

          dpkg-deb -Zxz --build "$DEB_DIR" "${PKGNAME}_${VERSION}.deb"

          echo "Package built: ${PKGNAME}_${VERSION}.deb"
          EOF
          
          # Make script executable and run it
          chmod +x build.sh
          ./build.sh
          cd ..
          mkdir -p termuxify/pool
          mv termuxify-src/termuxify_*.deb termuxify/pool/

      - name: Rebuild APT metadata
        run: |
          cd termuxify
          for arch in all arm arm64; do
            mkdir -p dists/stable/main/binary-$arch
            dpkg-scanpackages -a $arch pool /dev/null > dists/stable/main/binary-$arch/Packages
            gzip -fk dists/stable/main/binary-$arch/Packages
          done

      - name: Commit and push updates
        run: |
          git add . 
          git commit -m "Auto: updated APT repo with latest termuxify build" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
