name: Update APT Repo with Termuxify

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout APT Repo
        uses: actions/checkout@v3

      - name: Set up Git for pushing
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Clone termuxify source repo
        run: |
          git clone https://github.com/Ayanrajpoot10/termuxify.git termuxify-src

      - name: Install build tools
        run: |
          sudo apt update
          sudo apt install -y dpkg-dev build-essential devscripts

      - name: Build the .deb package
        run: |
          cd termuxify-src
          chmod +x build.sh
          ./build.sh ${{ github.event.inputs.version }}
          cd ..
          mkdir -p termuxify/pool/main/t/termuxify
          mv termuxify-src/*.deb termuxify/pool/main/t/termuxify/ || true
          # Keep only the latest .deb file
          cd termuxify/pool/main/t/termuxify/
          ls -t *.deb | tail -n +2 | xargs -r rm --
          cd ../../../../
          rm -rf termuxify-src

      - name: Rebuild APT metadata
        run: |
          cd termuxify
          # Debug: Print current directory and files
          pwd
          ls -R pool/main/t/termuxify/
          
          # Update only version and date in Release file
          mkdir -p dists/stable/main
          sed -i "s/^Version:.*/Version: ${{ github.event.inputs.version }}/" dists/stable/Release
          sed -i "s/^Date:.*/Date: $(date -u '+%a, %d %b %Y %H:%M:%S UTC')/" dists/stable/Release

          # Generate package metadata using dpkg-scanpackages
          for arch in all arm arm64; do
            mkdir -p dists/stable/main/binary-$arch
            dpkg-scanpackages pool /dev/null > dists/stable/main/binary-$arch/Packages
            gzip -c dists/stable/main/binary-$arch/Packages > dists/stable/main/binary-$arch/Packages.gz
          done

      - name: Commit and push updates
        run: |
          git add termuxify/
          git commit -m "Auto: updated APT repo with latest termuxify build" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/Ayanrajpoot10/Ayanrajpoot10.github.io.git
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
